// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sold_Machine_Project.Contexts;

namespace Sold_Machine_Project.Migrations
{
    [DbContext(typeof(AssetsInfoContext))]
    partial class AssetsInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sold_Machine_Project.Entities.Assets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("assetName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("assetSeries")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("machineName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            id = 1,
                            assetName = "Cutter head",
                            assetSeries = "S6",
                            machineName = "C300"
                        },
                        new
                        {
                            id = 2,
                            assetName = "Cutter head",
                            assetSeries = "S7",
                            machineName = "C40"
                        },
                        new
                        {
                            id = 3,
                            assetName = "Blade safety cover",
                            assetSeries = "S10",
                            machineName = "C300"
                        },
                        new
                        {
                            id = 4,
                            assetName = "Blade safety cover",
                            assetSeries = "S11",
                            machineName = "C60"
                        },
                        new
                        {
                            id = 5,
                            assetName = "Deburring blades",
                            assetSeries = "S6",
                            machineName = "C300"
                        },
                        new
                        {
                            id = 6,
                            assetName = "Cutter head",
                            assetSeries = "S8",
                            machineName = "C60"
                        },
                        new
                        {
                            id = 7,
                            assetName = "Clamping fixture",
                            assetSeries = "S2",
                            machineName = "C60"
                        },
                        new
                        {
                            id = 8,
                            assetName = "Blade safety cover",
                            assetSeries = "S11",
                            machineName = "C40"
                        },
                        new
                        {
                            id = 9,
                            assetName = "Shutter gripper",
                            assetSeries = "S3",
                            machineName = "C40"
                        },
                        new
                        {
                            id = 10,
                            assetName = "Shutter gripper",
                            assetSeries = "S4",
                            machineName = "C10"
                        },
                        new
                        {
                            id = 11,
                            assetName = "Cutter head",
                            assetSeries = "S2",
                            machineName = "C10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
